version: "3.5"

networks:
  kafka:
    driver: overlay
    attachable: true

configs:
  mm2.properties:
    file: ./mm2.properties

services:
  mmv2:
    image: lozuwa/kafka:mmv2-v2.5.0
    configs:
      - source: mm2.properties 
        target: /opt/kafka/configuration-files/mm2.properties
    environment:
      KAFKA_HEAP_OPTS: "-Xmx2G -Xms2G"
      TOPIC_REPLICATION_MAPS: "source_topic_1:target_topic_1,source_topic_2:target_topic_2"
    networks:
      - kafka
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        order: stop-first
        monitor: 25000ms
      restart_policy:
        condition: on-failure
        max_attempts: 20

