version: "3.5"

networks:
  kafka:
    driver: overlay
    attachable: true
    
services:
  zookeeper-source:
    image: zookeeper:3.4.12
    networks:
      - kafka 
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        order: stop-first
        monitor: 25000ms
      restart_policy:
        condition: on-failure
        max_attempts: 20

